/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_aff;

import bean.Affecter;
import bean.Employee;
import bean.Lieu;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manager.AffecterManager;
import manager.EmployeeManager;
import manager.LieuManager;

/**
 *
 * @author ELOIC
 */
public class InterfaceAppAff extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public InterfaceAppAff() {
        initComponents();
        afficher_employee();
        afficher_lieu();
        afficher_affectation();
    }
    
    
    
    public void afficher_employee() {
        try {
            EmployeeManager em = new EmployeeManager();
            List<bean.Employee> employees = em.listeEmployee();
            employees.sort(Comparator.comparingInt(Employee::getCodeemp));
            
            DefaultTableModel RecordTable = (DefaultTableModel) tableau_liste_emp.getModel();
            RecordTable.setRowCount(0);
            
            for (Employee employee : employees) {
                RecordTable.addRow(new Object[]{
                    employee.getCodeemp(),
                    employee.getNom(),
                    employee.getPrenom(),
                    employee.getPoste()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        texte_codeemp.setText("");
        texte_nom_emp.setText("");
        texte_prenom_emp.setText("");
        texte_poste_emp.setText("");
        texte_recherche_emp.setText("");
    }
    
    public void afficher_lieu() {
        try {
            LieuManager lm = new LieuManager();
            List<bean.Lieu> lieux = lm.listeLieu();
            lieux.sort(Comparator.comparingInt(Lieu::getCodelieu));
            
            DefaultTableModel RecordTable = (DefaultTableModel) tableau_liste_lieu.getModel();
            RecordTable.setRowCount(0);
            
            for (Lieu lieu : lieux) {
                RecordTable.addRow(new Object[]{
                    lieu.getCodelieu(),
                    lieu.getDesignation(),
                    lieu.getProvince()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        texte_codelieu.setText("");
        texte_designation.setText("");
        texte_province.setText("");
    }
    
    public void afficher_affectation() {
        try {
            AffecterManager am = new AffecterManager();
            List<bean.Affecter> affectations = am.listeAffectation();
            affectations.sort(Comparator.comparingInt(Affecter::getCodeemp));
            
            DefaultTableModel RecordTable = (DefaultTableModel) tableau_liste_aff.getModel();
            RecordTable.setRowCount(0);
            
            for (Affecter aff : affectations) {
                RecordTable.addRow(new Object[]{
                    aff.getCodeemp(),
                    aff.getCodelieu(),
                    aff.getDate()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        texte_codeemp_aff.setText("");
        texte_codelieu_aff.setText("");
        date_chooser_aff.setDate(new Date());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bouttons = new javax.swing.JPanel();
        btn_employee = new javax.swing.JButton();
        btn_lieu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panel_principale = new javax.swing.JPanel();
        panel_employee = new javax.swing.JPanel();
        panel_crud_employee = new javax.swing.JPanel();
        label_titre_employee = new javax.swing.JLabel();
        label_nom_emp = new javax.swing.JLabel();
        label_prenom_emp = new javax.swing.JLabel();
        label_poste_emp = new javax.swing.JLabel();
        texte_nom_emp = new javax.swing.JTextField();
        texte_prenom_emp = new javax.swing.JTextField();
        texte_poste_emp = new javax.swing.JTextField();
        panel_bouttons_crud = new javax.swing.JPanel();
        btn_ajout_emp = new javax.swing.JButton();
        btn_modif_emp = new javax.swing.JButton();
        btn_suppr_emp = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        texte_recherche_emp = new javax.swing.JTextField();
        btn_rech_emp = new javax.swing.JButton();
        label_codeemp = new javax.swing.JLabel();
        texte_codeemp = new javax.swing.JTextField();
        panel_liste_employee = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau_liste_emp = new javax.swing.JTable();
        panel_lieu = new javax.swing.JPanel();
        panel_crud_lieu = new javax.swing.JPanel();
        label_titre_lieu = new javax.swing.JLabel();
        label_designation = new javax.swing.JLabel();
        label_province = new javax.swing.JLabel();
        texte_designation = new javax.swing.JTextField();
        texte_province = new javax.swing.JTextField();
        panel_bouttons_crud1 = new javax.swing.JPanel();
        btn_ajout_lieu = new javax.swing.JButton();
        btn_modif_lieu = new javax.swing.JButton();
        btn_suppr_lieu = new javax.swing.JButton();
        btn_refresh_lieu = new javax.swing.JButton();
        label_codelieu = new javax.swing.JLabel();
        texte_codelieu = new javax.swing.JTextField();
        panel_liste_lieu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableau_liste_lieu = new javax.swing.JTable();
        panel_affectation = new javax.swing.JPanel();
        panel_crud_lieu1 = new javax.swing.JPanel();
        label_titre_aff = new javax.swing.JLabel();
        label_codelieu_aff = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        texte_codelieu_aff = new javax.swing.JTextField();
        panel_bouttons_crud2 = new javax.swing.JPanel();
        btn_ajout_aff = new javax.swing.JButton();
        btn_modif_aff = new javax.swing.JButton();
        btn_suppr_aff = new javax.swing.JButton();
        btn_refresh_aff = new javax.swing.JButton();
        label_codeemp_aff = new javax.swing.JLabel();
        texte_codeemp_aff = new javax.swing.JTextField();
        date_chooser_aff = new com.toedter.calendar.JDateChooser();
        panel_liste_lieu1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableau_liste_aff = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_bouttons.setBackground(new java.awt.Color(255, 255, 0));

        btn_employee.setText("Employee");
        btn_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employeeActionPerformed(evt);
            }
        });

        btn_lieu.setText("Lieu");
        btn_lieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lieuActionPerformed(evt);
            }
        });

        jButton1.setText("Affectation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_bouttonsLayout = new javax.swing.GroupLayout(panel_bouttons);
        panel_bouttons.setLayout(panel_bouttonsLayout);
        panel_bouttonsLayout.setHorizontalGroup(
            panel_bouttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bouttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bouttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_lieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_bouttonsLayout.setVerticalGroup(
            panel_bouttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bouttonsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_lieu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_principale.setBackground(new java.awt.Color(255, 255, 0));
        panel_principale.setLayout(new java.awt.CardLayout());

        panel_employee.setBackground(new java.awt.Color(255, 255, 0));

        label_titre_employee.setText("FORMULAIRE EMPLOYEE");

        label_nom_emp.setText("Nom*");

        label_prenom_emp.setText("Prénom*");

        label_poste_emp.setText("Poste*");

        texte_prenom_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texte_prenom_empActionPerformed(evt);
            }
        });

        panel_bouttons_crud.setLayout(new java.awt.GridLayout(1, 0));

        btn_ajout_emp.setText("Ajouter");
        btn_ajout_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajout_empActionPerformed(evt);
            }
        });
        panel_bouttons_crud.add(btn_ajout_emp);

        btn_modif_emp.setText("Modifier");
        btn_modif_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modif_empActionPerformed(evt);
            }
        });
        panel_bouttons_crud.add(btn_modif_emp);

        btn_suppr_emp.setText("Supprimer");
        btn_suppr_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suppr_empActionPerformed(evt);
            }
        });
        panel_bouttons_crud.add(btn_suppr_emp);

        btn_refresh.setText("Rafraichir");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        panel_bouttons_crud.add(btn_refresh);

        btn_rech_emp.setText("Chercher un nom / prenom ou un code");
        btn_rech_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rech_empActionPerformed(evt);
            }
        });

        label_codeemp.setText("Code_emp");

        javax.swing.GroupLayout panel_crud_employeeLayout = new javax.swing.GroupLayout(panel_crud_employee);
        panel_crud_employee.setLayout(panel_crud_employeeLayout);
        panel_crud_employeeLayout.setHorizontalGroup(
            panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crud_employeeLayout.createSequentialGroup()
                .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_crud_employeeLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_prenom_emp)
                            .addComponent(label_nom_emp)
                            .addComponent(label_poste_emp)
                            .addComponent(label_codeemp))
                        .addGap(43, 43, 43)
                        .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texte_codeemp, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(texte_nom_emp)
                                .addComponent(texte_prenom_emp)
                                .addComponent(texte_poste_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_rech_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_crud_employeeLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(label_titre_employee))
                    .addGroup(panel_crud_employeeLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_bouttons_crud, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texte_recherche_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel_crud_employeeLayout.setVerticalGroup(
            panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_crud_employeeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(label_titre_employee)
                .addGap(18, 18, 18)
                .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texte_recherche_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_rech_emp))
                .addGap(22, 22, 22)
                .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texte_codeemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_codeemp))
                .addGap(18, 18, 18)
                .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nom_emp)
                    .addComponent(texte_nom_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_prenom_emp)
                    .addComponent(texte_prenom_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_crud_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_poste_emp)
                    .addComponent(texte_poste_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(panel_bouttons_crud, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        panel_liste_employee.setLayout(new java.awt.GridLayout(1, 0));

        tableau_liste_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Codeemp", "Nom", "Prénom", "Poste"
            }
        ));
        tableau_liste_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableau_liste_empMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableau_liste_emp);
        if (tableau_liste_emp.getColumnModel().getColumnCount() > 0) {
            tableau_liste_emp.getColumnModel().getColumn(3).setHeaderValue("Poste");
        }

        panel_liste_employee.add(jScrollPane1);

        javax.swing.GroupLayout panel_employeeLayout = new javax.swing.GroupLayout(panel_employee);
        panel_employee.setLayout(panel_employeeLayout);
        panel_employeeLayout.setHorizontalGroup(
            panel_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_employeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_crud_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_liste_employee, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_employeeLayout.setVerticalGroup(
            panel_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_employeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_crud_employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_liste_employee, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_principale.add(panel_employee, "card2");

        panel_lieu.setBackground(new java.awt.Color(255, 255, 0));

        label_titre_lieu.setText("FORMULAIRE LIEU");

        label_designation.setText("Designation*");

        label_province.setText("Province*");

        texte_province.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texte_provinceActionPerformed(evt);
            }
        });

        panel_bouttons_crud1.setLayout(new java.awt.GridLayout());

        btn_ajout_lieu.setText("Ajouter");
        btn_ajout_lieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajout_lieuActionPerformed(evt);
            }
        });
        panel_bouttons_crud1.add(btn_ajout_lieu);

        btn_modif_lieu.setText("Modifier");
        btn_modif_lieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modif_lieuActionPerformed(evt);
            }
        });
        panel_bouttons_crud1.add(btn_modif_lieu);

        btn_suppr_lieu.setText("Supprimer");
        btn_suppr_lieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suppr_lieuActionPerformed(evt);
            }
        });
        panel_bouttons_crud1.add(btn_suppr_lieu);

        btn_refresh_lieu.setText("Rafraichir");
        btn_refresh_lieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_lieuActionPerformed(evt);
            }
        });
        panel_bouttons_crud1.add(btn_refresh_lieu);

        label_codelieu.setText("Code_lieu");

        javax.swing.GroupLayout panel_crud_lieuLayout = new javax.swing.GroupLayout(panel_crud_lieu);
        panel_crud_lieu.setLayout(panel_crud_lieuLayout);
        panel_crud_lieuLayout.setHorizontalGroup(
            panel_crud_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crud_lieuLayout.createSequentialGroup()
                .addGroup(panel_crud_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_crud_lieuLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panel_crud_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_province)
                            .addComponent(label_designation)
                            .addComponent(label_codelieu))
                        .addGap(43, 43, 43)
                        .addGroup(panel_crud_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texte_codelieu, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_crud_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(texte_designation, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(texte_province))))
                    .addGroup(panel_crud_lieuLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(label_titre_lieu))
                    .addGroup(panel_crud_lieuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panel_bouttons_crud1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel_crud_lieuLayout.setVerticalGroup(
            panel_crud_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_crud_lieuLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(label_titre_lieu)
                .addGap(63, 63, 63)
                .addGroup(panel_crud_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texte_codelieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_codelieu))
                .addGap(18, 18, 18)
                .addGroup(panel_crud_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_designation)
                    .addComponent(texte_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panel_crud_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_province)
                    .addComponent(texte_province, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(panel_bouttons_crud1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        panel_liste_lieu.setLayout(new java.awt.GridLayout());

        tableau_liste_lieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Codelieu", "Désignation", "Province"
            }
        ));
        tableau_liste_lieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableau_liste_lieuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableau_liste_lieu);

        panel_liste_lieu.add(jScrollPane2);

        javax.swing.GroupLayout panel_lieuLayout = new javax.swing.GroupLayout(panel_lieu);
        panel_lieu.setLayout(panel_lieuLayout);
        panel_lieuLayout.setHorizontalGroup(
            panel_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_crud_lieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_liste_lieu, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_lieuLayout.setVerticalGroup(
            panel_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_lieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_crud_lieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_liste_lieu, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_principale.add(panel_lieu, "card3");

        panel_affectation.setBackground(new java.awt.Color(255, 255, 0));

        label_titre_aff.setText("FORMULAIRE AFFECTATION");

        label_codelieu_aff.setText("Code_lieu*");

        label_date.setText("Date*");

        panel_bouttons_crud2.setLayout(new java.awt.GridLayout());

        btn_ajout_aff.setText("Ajouter");
        btn_ajout_aff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajout_affActionPerformed(evt);
            }
        });
        panel_bouttons_crud2.add(btn_ajout_aff);

        btn_modif_aff.setText("Modifier");
        btn_modif_aff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modif_affActionPerformed(evt);
            }
        });
        panel_bouttons_crud2.add(btn_modif_aff);

        btn_suppr_aff.setText("Supprimer");
        btn_suppr_aff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suppr_affActionPerformed(evt);
            }
        });
        panel_bouttons_crud2.add(btn_suppr_aff);

        btn_refresh_aff.setText("Rafraichir");
        btn_refresh_aff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_affActionPerformed(evt);
            }
        });
        panel_bouttons_crud2.add(btn_refresh_aff);

        label_codeemp_aff.setText("Code_emp*");

        javax.swing.GroupLayout panel_crud_lieu1Layout = new javax.swing.GroupLayout(panel_crud_lieu1);
        panel_crud_lieu1.setLayout(panel_crud_lieu1Layout);
        panel_crud_lieu1Layout.setHorizontalGroup(
            panel_crud_lieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crud_lieu1Layout.createSequentialGroup()
                .addGroup(panel_crud_lieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_crud_lieu1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panel_crud_lieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_date)
                            .addComponent(label_codelieu_aff)
                            .addComponent(label_codeemp_aff))
                        .addGap(43, 43, 43)
                        .addGroup(panel_crud_lieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texte_codeemp_aff, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(texte_codelieu_aff, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(date_chooser_aff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_crud_lieu1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(label_titre_aff))
                    .addGroup(panel_crud_lieu1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panel_bouttons_crud2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panel_crud_lieu1Layout.setVerticalGroup(
            panel_crud_lieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_crud_lieu1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(label_titre_aff)
                .addGap(63, 63, 63)
                .addGroup(panel_crud_lieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texte_codeemp_aff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_codeemp_aff))
                .addGap(18, 18, 18)
                .addGroup(panel_crud_lieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_codelieu_aff)
                    .addComponent(texte_codelieu_aff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_crud_lieu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_date)
                    .addComponent(date_chooser_aff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(panel_bouttons_crud2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        panel_liste_lieu1.setLayout(new java.awt.GridLayout());

        tableau_liste_aff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Codeemp", "Codelieu", "Date"
            }
        ));
        tableau_liste_aff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableau_liste_affMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableau_liste_aff);

        panel_liste_lieu1.add(jScrollPane3);

        javax.swing.GroupLayout panel_affectationLayout = new javax.swing.GroupLayout(panel_affectation);
        panel_affectation.setLayout(panel_affectationLayout);
        panel_affectationLayout.setHorizontalGroup(
            panel_affectationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_affectationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_crud_lieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_liste_lieu1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_affectationLayout.setVerticalGroup(
            panel_affectationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_affectationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_affectationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_crud_lieu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_liste_lieu1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_principale.add(panel_affectation, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_bouttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_principale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_bouttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_employeeActionPerformed
        // Acces au panel Employee
        panel_principale.removeAll();
        panel_principale.add(panel_employee);
        panel_principale.repaint();
        panel_principale.revalidate();
    }//GEN-LAST:event_btn_employeeActionPerformed

    private void btn_lieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lieuActionPerformed
        // Acces au panel Lieu
        panel_principale.removeAll();
        panel_principale.add(panel_lieu);
        panel_principale.repaint();
        panel_principale.revalidate();
    }//GEN-LAST:event_btn_lieuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Acces au panel Affectation
        panel_principale.removeAll();
        panel_principale.add(panel_affectation);
        panel_principale.repaint();
        panel_principale.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void texte_prenom_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texte_prenom_empActionPerformed
    }//GEN-LAST:event_texte_prenom_empActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        afficher_employee();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_ajout_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajout_empActionPerformed
        
        String nom = texte_nom_emp.getText();
        String prenom = texte_prenom_emp.getText();
        String poste = texte_poste_emp.getText();
        
        if (texte_nom_emp.getText().isBlank() && texte_prenom_emp.getText().isBlank() && texte_poste_emp.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs de texte!");
        } else {
            EmployeeManager em = new EmployeeManager();
            em.ajouterEmployee(nom, prenom, poste);
            
            JOptionPane.showMessageDialog(null, "Employée ajouté avec succès");
            afficher_employee();

        }
        
        afficher_employee();
        
    }//GEN-LAST:event_btn_ajout_empActionPerformed

    private void btn_modif_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modif_empActionPerformed
        
        String codeemp = texte_codeemp.getText();
        int icodeemp = Integer.parseInt(codeemp);
        String nom = texte_nom_emp.getText();
        String prenom = texte_prenom_emp.getText();
        String poste = texte_poste_emp.getText();
        
        if (texte_codeemp.getText().isBlank() && texte_nom_emp.getText().isBlank() && texte_prenom_emp.getText().isBlank() && texte_poste_emp.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs de texte!");
        } else {
            EmployeeManager em = new EmployeeManager();
            em.modifierEmployee(icodeemp, nom, prenom, poste);
            
            JOptionPane.showMessageDialog(null, "Employée modifié avec succès");

        }
        
        afficher_employee();
        
    }//GEN-LAST:event_btn_modif_empActionPerformed

    private void btn_suppr_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suppr_empActionPerformed
        
        if (texte_codeemp.getText().isBlank() && texte_nom_emp.getText().isBlank() && texte_prenom_emp.getText().isBlank() && texte_poste_emp.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Aucun employée à supprimer. \nVeuillez selectionner un employée dans le tableau avant la suppression !");
        } else {
            EmployeeManager em = new EmployeeManager();
            em.supprimerEmployee(Integer.parseInt(texte_codeemp.getText()));
            
            
            JOptionPane.showMessageDialog(null, "Suppression effectuée avec succès");

        }
        
        afficher_employee();
        
    }//GEN-LAST:event_btn_suppr_empActionPerformed

    private void btn_rech_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rech_empActionPerformed
        Object codeemp = texte_recherche_emp.getText();
        
        try {
            EmployeeManager em = new EmployeeManager();
            List<bean.Employee> employee = (List<bean.Employee>) em.chercherNomCodeEmp(codeemp);
            employee.sort(Comparator.comparingInt(Employee::getCodeemp));
            
            
            DefaultTableModel RecordTable = (DefaultTableModel) tableau_liste_emp.getModel();
            RecordTable.setRowCount(0);
            
            for (Employee emp : employee) {
                RecordTable.addRow(new Object[]{
                    emp.getCodeemp(),
                    emp.getNom(),
                    emp.getPrenom(),
                    emp.getPoste()
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btn_rech_empActionPerformed

    private void tableau_liste_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableau_liste_empMouseClicked
        int row = tableau_liste_emp.getSelectedRow();
        String codeemp = tableau_liste_emp.getModel().getValueAt(row, 0).toString();
        int icodeemp = Integer.parseInt(codeemp);
        
        try {
            EmployeeManager em = new EmployeeManager();
            List<bean.Employee> employee = (List<bean.Employee>) em.chercherCodeEmp(icodeemp);
            employee.sort(Comparator.comparingInt(Employee::getCodeemp));
            
            for (Employee emp : employee) {
                texte_codeemp.setText(Integer.toString(emp.getCodeemp()));
                texte_nom_emp.setText(emp.getNom());
                texte_prenom_emp.setText(emp.getPrenom());
                texte_poste_emp.setText(emp.getPoste());
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_tableau_liste_empMouseClicked

    private void texte_provinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texte_provinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texte_provinceActionPerformed

    private void btn_ajout_lieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajout_lieuActionPerformed
        
        String designation = texte_designation.getText();
        String province = texte_province.getText();
        
        if (texte_designation.getText().isBlank() && texte_province.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs de texte!");
        } else {
            LieuManager lm = new LieuManager();
            lm.ajouterLieu(designation, province);
            
            JOptionPane.showMessageDialog(null, "Lieu ajouté avec succès");
            afficher_employee();

        }
        
        afficher_lieu();
        
    }//GEN-LAST:event_btn_ajout_lieuActionPerformed

    private void btn_modif_lieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modif_lieuActionPerformed
        
        String codelieu = texte_codelieu.getText();
        int icodelieu = Integer.parseInt(codelieu);
        String designation = texte_designation.getText();
        String province = texte_province.getText();
        
        if (texte_designation.getText().isBlank() && texte_province.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs de texte!");
        } else {
            LieuManager lm = new LieuManager();
            lm.modifierLieu(icodelieu, designation, province);
            
            JOptionPane.showMessageDialog(null, "Lieu modifié avec succès");

        }
        
        afficher_lieu();
        
    }//GEN-LAST:event_btn_modif_lieuActionPerformed

    private void btn_suppr_lieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suppr_lieuActionPerformed
        
        if (texte_codelieu.getText().isBlank() && texte_designation.getText().isBlank() && texte_province.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Aucun lieu à supprimer. \nVeuillez selectionner un lieu dans le tableau avant la suppression !");
        } else {
            LieuManager lm = new LieuManager();
            lm.supprimerLieu(Integer.parseInt(texte_codelieu.getText()));
            
            
            JOptionPane.showMessageDialog(null, "Suppression effectuée avec succès");

        }
        
        afficher_lieu();
        
    }//GEN-LAST:event_btn_suppr_lieuActionPerformed

    private void btn_refresh_lieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_lieuActionPerformed
        afficher_lieu();
    }//GEN-LAST:event_btn_refresh_lieuActionPerformed

    private void tableau_liste_lieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableau_liste_lieuMouseClicked
        int row = tableau_liste_lieu.getSelectedRow();
        String codelieu = tableau_liste_lieu.getModel().getValueAt(row, 0).toString();
        int icodelieu = Integer.parseInt(codelieu);
        
        try {
            LieuManager lm = new LieuManager();
            List<bean.Lieu> lieu = (List<bean.Lieu>) lm.chercherCodeLieu(icodelieu);
            lieu.sort(Comparator.comparingInt(Lieu::getCodelieu));
            
            for (Lieu l : lieu) {
                texte_codelieu.setText(Integer.toString(l.getCodelieu()));
                texte_designation.setText(l.getDesignation());
                texte_province.setText(l.getProvince());
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_tableau_liste_lieuMouseClicked

    private void btn_ajout_affActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajout_affActionPerformed
        
        int codeemp = Integer.parseInt(texte_codeemp_aff.getText());
        int codelieu = Integer.parseInt(texte_codelieu_aff.getText());
        Date date = date_chooser_aff.getDate();
        
        if (texte_codeemp_aff.getText().isBlank() || texte_codelieu_aff.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs de texte!");
        } else {
            AffecterManager am = new AffecterManager();
            am.ajouterAffectation(codeemp, codelieu, date);
            
            JOptionPane.showMessageDialog(null, "Affectation ajoutée avec succès");
            afficher_affectation();

        }
        
        afficher_lieu();
        
    }//GEN-LAST:event_btn_ajout_affActionPerformed

    private void btn_modif_affActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modif_affActionPerformed
        
        int codeemp = Integer.parseInt(texte_codeemp_aff.getText());
        int codelieu = Integer.parseInt(texte_codelieu_aff.getText());
        Date date = date_chooser_aff.getDate();
        
        if (texte_codeemp_aff.getText().isBlank() && texte_codelieu_aff.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs de texte!");
        } else {
            AffecterManager am = new AffecterManager();
            am.modifierAffectation(codeemp, codelieu, date);
            
            JOptionPane.showMessageDialog(null, "Affectation modifié avec succès");

        }
        
        afficher_affectation();
        
    }//GEN-LAST:event_btn_modif_affActionPerformed

    private void btn_suppr_affActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suppr_affActionPerformed
        
        int codeemp = Integer.parseInt(texte_codeemp_aff.getText());
        int codelieu = Integer.parseInt(texte_codelieu_aff.getText());
        Date date = date_chooser_aff.getDate();
        
        if (texte_codeemp_aff.getText().isBlank() && texte_codelieu_aff.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs de texte!");
        } else {
            AffecterManager am = new AffecterManager();
            am.supprimerAffectation(codeemp, codelieu, date);
            
            
            JOptionPane.showMessageDialog(null, "Suppression effectuée avec succès");

        }
        
        afficher_affectation();
        
    }//GEN-LAST:event_btn_suppr_affActionPerformed

    private void btn_refresh_affActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_affActionPerformed
        afficher_affectation();
    }//GEN-LAST:event_btn_refresh_affActionPerformed

    private void tableau_liste_affMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableau_liste_affMouseClicked
        int row = tableau_liste_aff.getSelectedRow();
        String codeemp = tableau_liste_aff.getModel().getValueAt(row, 0).toString();
        int icodeemp = Integer.parseInt(codeemp);
        String codelieu = tableau_liste_aff.getModel().getValueAt(row, 1).toString();
        int icodelieu = Integer.parseInt(codelieu);
//        String date = tableau_liste_aff.getModel().getValueAt(row, 2).toString();
//        Date ddate = new Date(date);
        
        
        try {
            AffecterManager am = new AffecterManager();
            List<bean.Affecter> aff = (List<bean.Affecter>) am.chercherAff(icodeemp, icodelieu);
//            List<bean.Affecter> aff = (List<bean.Affecter>) am.chercherAff(icodeemp, icodelieu, ddate);
            aff.sort(Comparator.comparingInt(Affecter::getCodeemp));
            
            for (Affecter a : aff) {
                texte_codeemp_aff.setText(Integer.toString(a.getCodeemp()));
                texte_codelieu_aff.setText(Integer.toString(a.getCodelieu()));
                date_chooser_aff.setDate(a.getDate());
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_tableau_liste_affMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAppAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAppAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAppAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAppAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfaceAppAff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajout_aff;
    private javax.swing.JButton btn_ajout_emp;
    private javax.swing.JButton btn_ajout_lieu;
    private javax.swing.JButton btn_employee;
    private javax.swing.JButton btn_lieu;
    private javax.swing.JButton btn_modif_aff;
    private javax.swing.JButton btn_modif_emp;
    private javax.swing.JButton btn_modif_lieu;
    private javax.swing.JButton btn_rech_emp;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_refresh_aff;
    private javax.swing.JButton btn_refresh_lieu;
    private javax.swing.JButton btn_suppr_aff;
    private javax.swing.JButton btn_suppr_emp;
    private javax.swing.JButton btn_suppr_lieu;
    private com.toedter.calendar.JDateChooser date_chooser_aff;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_codeemp;
    private javax.swing.JLabel label_codeemp_aff;
    private javax.swing.JLabel label_codelieu;
    private javax.swing.JLabel label_codelieu_aff;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_designation;
    private javax.swing.JLabel label_nom_emp;
    private javax.swing.JLabel label_poste_emp;
    private javax.swing.JLabel label_prenom_emp;
    private javax.swing.JLabel label_province;
    private javax.swing.JLabel label_titre_aff;
    private javax.swing.JLabel label_titre_employee;
    private javax.swing.JLabel label_titre_lieu;
    private javax.swing.JPanel panel_affectation;
    private javax.swing.JPanel panel_bouttons;
    private javax.swing.JPanel panel_bouttons_crud;
    private javax.swing.JPanel panel_bouttons_crud1;
    private javax.swing.JPanel panel_bouttons_crud2;
    private javax.swing.JPanel panel_crud_employee;
    private javax.swing.JPanel panel_crud_lieu;
    private javax.swing.JPanel panel_crud_lieu1;
    private javax.swing.JPanel panel_employee;
    private javax.swing.JPanel panel_lieu;
    private javax.swing.JPanel panel_liste_employee;
    private javax.swing.JPanel panel_liste_lieu;
    private javax.swing.JPanel panel_liste_lieu1;
    private javax.swing.JPanel panel_principale;
    private javax.swing.JTable tableau_liste_aff;
    private javax.swing.JTable tableau_liste_emp;
    private javax.swing.JTable tableau_liste_lieu;
    private javax.swing.JTextField texte_codeemp;
    private javax.swing.JTextField texte_codeemp_aff;
    private javax.swing.JTextField texte_codelieu;
    private javax.swing.JTextField texte_codelieu_aff;
    private javax.swing.JTextField texte_designation;
    private javax.swing.JTextField texte_nom_emp;
    private javax.swing.JTextField texte_poste_emp;
    private javax.swing.JTextField texte_prenom_emp;
    private javax.swing.JTextField texte_province;
    private javax.swing.JTextField texte_recherche_emp;
    // End of variables declaration//GEN-END:variables
}
